### PR TITLE
rbenv init with no-rehash

### PR DESCRIPTION
**Pull request by neckhair**
`rbenv init` rehashes all the shims by default. This can make new console session start very slowly. Adding the `--no-rehash` option makes things a lot faster. You can still rehash manually.

### CODE REVIEW

**Comment by seanknox** [comment]
@neckhair Can you explain in more detail? How slow is slow and what's the use case for this PR?

**Comment by eugeneius** [comment]
I added some code to [this file](https://github.com/boxen/puppet-boxen/blob/master/templates/env.sh.erb) to print how long each script in `env.d/` takes to run.

```patch
 for f in $BOXEN_HOME/env.d/*.sh ; do
   if [ -f $f ] ; then
+    START=$(gdate +%s%N)
     source $f
+    END=$(gdate +%s%N)
+    DURATION=$(expr \( $END - $START \) / 1000000)
+    echo "$f: ${DURATION}ms"
   fi
 done
```

## Before

```
/opt/boxen/env.d/10_brewcask.sh: 7ms
/opt/boxen/env.d/10_config.sh: 4ms
/opt/boxen/env.d/10_homebrew.sh: 6ms
/opt/boxen/env.d/30_gh_creds.sh: 4ms
/opt/boxen/env.d/30_mysql.sh: 4ms
/opt/boxen/env.d/30_nodejs.sh: 52ms
/opt/boxen/env.d/30_phantomjs.sh: 89ms
/opt/boxen/env.d/30_ruby.sh: 761ms
/opt/boxen/env.d/70_elasticsearch.sh: 4ms
/opt/boxen/env.d/70_memcached.sh: 4ms
/opt/boxen/env.d/70_mongodb.sh: 5ms
/opt/boxen/env.d/70_postgresql.sh: 5ms
/opt/boxen/env.d/70_redis.sh: 6ms
/opt/boxen/env.d/90_boxen_autocomplete.sh: 5ms
/opt/boxen/env.d/90_relative_bin_on_path.sh: 5ms
```

## After

```
/opt/boxen/env.d/10_brewcask.sh: 4ms
/opt/boxen/env.d/10_config.sh: 9ms
/opt/boxen/env.d/10_homebrew.sh: 4ms
/opt/boxen/env.d/30_gh_creds.sh: 5ms
/opt/boxen/env.d/30_mysql.sh: 4ms
/opt/boxen/env.d/30_nodejs.sh: 59ms
/opt/boxen/env.d/30_phantomjs.sh: 74ms
/opt/boxen/env.d/30_ruby.sh: 59ms
/opt/boxen/env.d/70_elasticsearch.sh: 4ms
/opt/boxen/env.d/70_memcached.sh: 4ms
/opt/boxen/env.d/70_mongodb.sh: 5ms
/opt/boxen/env.d/70_postgresql.sh: 4ms
/opt/boxen/env.d/70_redis.sh: 4ms
/opt/boxen/env.d/90_boxen_autocomplete.sh: 4ms
/opt/boxen/env.d/90_relative_bin_on_path.sh: 4ms
```

## Result

700ms faster! :rocket: 

I do have 12 rubies and 117 shims though, so I might be an outlier. The creator of rbenv also rejected a proposal for this behaviour to be the default: https://github.com/rbenv/rbenv/issues/304#issuecomment-11793124

Maybe this should be implemented as a configuration option managed with Hiera instead?

**Comment by jacobbednarz** [comment]
> I do have 12 rubies and 117 shims though, so I might be an outlier. 

Definitely not an outlier. There are _many_ people running ridiculous numbers of rubies and shims on their local setups.

In saying that, I'm afraid I'm going to side with Sam on this one as I'm of a similar opinion that the UX outweighs the performance gains here. I would be open to putting this in as a hiera option though so that people can opt in should they need that performance win. My only concern would be making sure that this script is able to pull the data from hiera as I'm not 100% if this is done within the puppet run or before hand.

**Comment by mislav** [comment]
Thanks for the suggestion, and sorry that `rbenv rehash` was so slow before. Instead of this change, I'm going to have this project depend on rbenv 1.0 by default, which makes `rbenv rehash` much faster, so that won't be such an issue anymore.

**Comment by mislav** [comment]
Upgrading to at least rbenv 1.0 will result in a much faster `rbenv rehash` execution. This is now in default configuration: https://github.com/boxen/puppet-ruby/commit/9253aa5bb31c0bf3506ab445116e1f2d676ce313

**Pull request closed without merging**
