### PR TITLE
Fix plugin type throwing error when not installing through hiera yaml

### PR DESCRIPTION
**Pull request by salimane**
This pr fixes @dlackty problem https://github.com/boxen/puppet-ruby/pull/125#issuecomment-113871650 .
Thanks

### CODE REVIEW

**Comment by salimane** [comment]
any update here ?

**Comment by dieterdemeyer** [comment]
:+1: for getting this merged soon

**Comment by jacobbednarz** [comment]
Sorry @salimane - I haven't had a chance to look into the initial bug report. Will take a look this week.

On a side note, did you recently update your comment to include my mention? It says you posted it on the 2nd Aug however I got a notification on the 19th Dec.

**Comment by salimane** [comment]
@jacobbednarz yep I've just recently updated the comment to include your mention.

**Comment by salimane** [comment]
@jacobbednarz any update on this ?
Thanks

**Comment by jacobbednarz** [comment]
This looks sane and _should_ be fine to merge. I don't use any `rbenv` plugins so I can't comment on that front but the code looks to do what it says on the tin.

:+1:

**Comment by salimane** [comment]
any update on this ?

**Comment by jacobbednarz** [comment]
Thanks! :cake:

**Comment by salimane** [comment]
@jacobbednarz thanks, a new release would be appreciated.

**Comment by jacobbednarz** [comment]
this has been released in [8.5.6](https://github.com/boxen/puppet-ruby/tree/8.5.6)

**Pull request merged**
