### PR TITLE
Allows ruby_version to be an array

### PR DESCRIPTION
**Pull request by stefanvermaas**
There are some use cases where you might want to specify several ruby versions for installing a ruby gem. Currently you're required to specify the gem multiple times if you want to exclude a specific ruby version(s). I thought it might be useful to also allow an array to be set for the ruby versions.

Some more thoughts on this: It might also be useful/be better to just add an `except` or `excludes` method that excludes some ruby versions. This might be a better approach to this problem, but I've got no idea how to implement this.

**Please note**: I wasn't able to test this, because I'm not entirely sure how to test this. I've got (close to) zero experience with these puppet/boxen packages. So if you think this is a nice feature, do you want to help me out with writing the specs for this?

**Additional footnote:** I believe the puppet version should be updated too, because running rspec gives the error message described in this issue: [Puppet raises an exception under Ruby 2.1](https://tickets.puppetlabs.com/browse/PUP-1266).

### CODE REVIEW

**Comment by seanknox** [comment]
@stefanvermaas To test, run `script/specs`. You'll need to use Ruby 2.x since as you noted the version of Puppet in the project errors on newer versions. Take a look at the example specs for test ideas.

**Comment by mislav** [comment]
Right now you must test on Ruby < 2.1 unfortunately. I'd like to see tests for this before merging.

**Comment by dgoodlad** [comment]
You should be testing on *system* ruby, since Boxen only ever executes using system ruby. At the moment, this means `ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]` for Yosemite.

`cd puppet-ruby && rbenv local system` should get you there.

**Comment by seanknox** [comment]
Hi @stefanvermaas, closing for now. Please re-open when you have tests. Thanks.

**Pull request closed without merging**
